style = "default"
indent = 4
margin = 92
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
import_to_using = true
remove_extra_newlines = true
short_to_long_function_def = true
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
# always_use_return = true
