style = "yas"
indent = 4
margin = 92
always_for_in = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = true
always_use_return = true
whitespace_in_kwargs = true
whitespace_typedefs = true
join_lines_based_on_source = true
separate_kwargs_with_semicolon = true
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
