name = "PortfolioOptimiser"
uuid = "748726ae-2fc6-4ae6-b81c-5fed3516a822"
authors = ["Daniel Celis Garza"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
