name: Aqua
on:
  push:
    branches:
      - main
      - release-*
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v3
      - name: Aqua
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(name="Aqua"))
          Pkg.develop(PackageSpec(path=pwd()))
          using PortfolioOptimiser, Aqua
          Aqua.test_all(PortfolioOptimiser, ambiguities = false, deps_compat = false)
          # Aqua.test_ambiguities(PortfolioOptimiser)
          # Aqua.test_unbound_args(PortfolioOptimiser)
          # Aqua.test_undefined_exports(PortfolioOptimiser)
          # Aqua.test_stale_deps(PortfolioOptimiser)
          # Aqua.test_piracy(PortfolioOptimiser)