name: Documenter
on:
  push:
    branches: [master, main, release-*, dev]
    tags: [v*]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Documenter:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@v1  # if package requires Pkg.build()
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}